### ISSUE TITLE
tbahdila

### ISSUE THREAD

**Issue by chrhi** [Chargily/chargily-epay-js#9]
![chargily](https://github.com/Chargily/chargily-epay-js/assets/116351398/3b1b3341-ebd9-43d1-ab58-88597cd4186a)

**Comment by karaOdin** [comment]
You can use or check documentation here https://dev.chargily.com/docs/pay-api

**Comment by rofazayn** [comment]
I don't think calling it "tbahdila" fits the subject of this issue, nor fits your professionalism as a developer.

I and @karaOdin are just collaborators in this repo, I personally don't have access or permission to publish this to NPM.

The library published to NPM is named `chargily-epay-gateway` and it is an older version, if you want to use it you can either:
- `npm i chargily-epay-gateway`
- `yarn add chargily-epay-gateway`

If you want to use the current version that doesn't give you headache while trying to validate the signature, you can browse the `src` folder and copy/integrate the logic from there into your code and edit it to fit your use case.

You can also find a working example in `src/examples`
